### ISSUE TITLE
Iterating through array : TypeError: undefined is not a function  

### ISSUE THREAD

**Issue by savvidis** [AbhinavMadahar/Easypedia#2]
Hello and thank you for the package. 

When I ran an array of words (using the two words from your example) I receive the following error after getting the 1st result.

Let me know if you have an idea of why this happens. 

Thanks

```

  name: 'Unidan',
  language: 'en' }

Users/sabbidis/meteor/andela/node_modules/easypedia/node_modules/wtf_wikipedia/lib/sentence_parser.js:30
      tmp[i] = tmp[i].replace(/^\s+|\s+$/g, "");
                      ^
TypeError: undefined is not a function
    at sentence_parser (/Users/sabbidis/meteor/andela/node_modules/easypedia/node_modules/wtf_wikipedia/lib/sentence_parser.js:30:23)
    at /Users/sabbidis/meteor/andela/node_modules/easypedia/node_modules/wtf_wikipedia/index.js:506:9
    at Array.forEach (native)
    at Object.main [as parse] (/Users/sabbidis/meteor/andela/node_modules/easypedia/node_modules/wtf_wikipedia/index.js:463:13)
    at module.exports (/Users/sabbidis/meteor/andela/node_modules/easypedia/compiled/parse.js:12:28)
    at /Users/sabbidis/meteor/andela/node_modules/easypedia/compiled/main.js:29:18
    at Request._callback (/Users/sabbidis/meteor/andela/node_modules/easypedia/node_modules/wtf_wikipedia/lib/fetch_text.js:18:5)
    at Request.self.callback (/Users/sabbidis/meteor/andela/node_modules/request/request.js:123:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/sabbidis/meteor/andela/node_modules/request/request.js:1047:14)
```

**Comment by AbhinavMadahar** [comment]
That's a bug with wtf_wikipedia that I fixed yesterday. Just run `npm remove easypedia && npm install easypedia` to update and fix it.

**Comment by savvidis** [comment]
thanks that made the trick.

However, something new came up. I am using the error variable as the return object as an unknown error stops the callback. 

So I am using this code 

```
 easypedia(upcase, function(error,result) {
        if (!!error && typeof(error) != "undefined"){       
            console.log(error.text.Intro[0].text);
        }
        if (typeof(result) != "undefined"){
            console.log(result[type]);
        }
        });
```
